<?php

namespace AppBundle\Repository;

/**
 * FormTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
