app_form_template:
    resource: "@AppBundle/Controller/FormTemplateController.php"
    type:     annotation

app_question:
    resource: "@AppBundle/Controller/QuestionController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation
